Name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build go application
        run: go build ./...
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_remote_url: ssh://dokku@78.46.204.127/taskeroo
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}